// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace KimchiGameplayTags
{
	// Input Tags
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump)
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip)
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquip)

	// Player Tags
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Weapon_Axe);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_Weapon_Axe);
	
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	

	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Weapon);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Weapon);
}
