// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGameplayTags
{
	// Input Tags
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquip);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	// Player Tags
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Weapon_Axe);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_Weapon_Axe);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Weapon);
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Weapon);

	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	// Enemy Tags
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	// Shared Tags
	SOULLIKEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
}
